import fs from "node:fs";
import assert from "node:assert/strict";

const root="app/src/main";
const main=fs.readFileSync(root+"/java/industries/leeway/pocket/MainActivity.kt","utf8");
const voice=fs.readFileSync(root+"/java/industries/leeway/pocket/PocketVoiceActivity.kt","utf8");
const voiceHost=fs.readFileSync(root+"/java/industries/leeway/pocket/PocketVoiceHost.kt","utf8");
const nativeVoice=fs.readFileSync(root+"/java/industries/leeway/pocket/NativeVoiceDecoder.kt","utf8");
const nativeContract=fs.readFileSync(root+"/java/industries/leeway/pocket/NativeDecoderContract.kt","utf8");
const gradle=fs.readFileSync("app/build.gradle.kts","utf8");
const overlay=fs.readFileSync(root+"/java/industries/leeway/pocket/PocketOverlayService.kt","utf8");
const bridge=fs.readFileSync(root+"/java/industries/leeway/pocket/DeviceBridgeClient.kt","utf8");
const bindings=fs.readFileSync(root+"/java/industries/leeway/pocket/EcosystemBindings.kt","utf8");
const skills=fs.readFileSync(root+"/java/industries/leeway/pocket/SkillAuthorityClient.kt","utf8");
const manifest=fs.readFileSync(root+"/AndroidManifest.xml","utf8");
const bindingJson=JSON.parse(fs.readFileSync("docs/ecosystem-bindings.json","utf8"));
const profile=JSON.parse(fs.readFileSync(root+"/assets/leeway-authority-profile.json","utf8"));
assert.equal(profile.creator.name,"Leonard J. Lee");
assert.equal(new Set(profile.repositories.map(x=>x.name)).size,9);
assert.equal(profile.imageGeneration.binding,"NOT_BOUND");
assert.match(profile.creator.classification,/NOT_AUTHENTICATION/);

assert.doesNotMatch(main,/TextToSpeech/);
assert.doesNotMatch(voice,/TextToSpeech/);
assert.doesNotMatch(voice,/speechSynthesis/);
assert.match(voice,/SpeechRecognizer/);
assert.match(voiceHost,/LeeWayAndroidVoice/);
assert.match(voiceHost,/DEFAULT_VOICE_ID = "agent-lee-voice-one"/);
assert.match(voiceHost,/agent_voice_one_default_v2/);
assert.doesNotMatch(voiceHost,/putString\("selected_id","android-installed-english"\)/);
assert.match(voiceHost,/previewAfterSelection=true/);
assert.match(voiceHost,/Voice One is ready/);
assert.match(voiceHost,/fun forceVoiceOne/);
assert.match(voiceHost,/fun diagnosticSnapshot/);
assert.match(voice,/FORCE AGENT LEE VOICE ONE/);
assert.match(voice,/SHOW VOICE DIAGNOSTIC/);
assert.match(nativeContract,/object NativeEncoderContract/);
assert.match(nativeVoice,/speech_encoder\.onnx/);
assert.match(nativeVoice,/04431dcef6325c54b02de2219845888b464bcd1f1ac2f8839c2fecd1ed2ef294/);
assert.match(nativeVoice,/@JavascriptInterface fun encode/);
assert.match(nativeVoice,/audio_features","audio_tokens","speaker_embeddings","speaker_features/);
assert.match(gradle,/versionCode = 18/);
assert.match(gradle,/versionName = "0\.2\.16-native-encoder-rc1"/);
assert.match(voice,/PocketSpeech.detach/);
assert.doesNotMatch(voice,/WebView\(/);
assert.match(voice,/agent\.chat/);
assert.match(voice,/canonicalFormulaState/);
assert.match(voice,/DeviceBridgeClient/);
assert.match(overlay,/TYPE_APPLICATION_OVERLAY/);
assert.match(overlay,/PocketVoiceActivity/);
assert.match(bridge,/PocketBridgeActivity/);
assert.match(bridge,/POCKET_BOOTSTRAP/);
assert.match(bindings,/ecosystem-bindings\.json/);
assert.match(skills,/96ea94dda56e642887e600b54528b69919f0a2e6/);
assert.match(skills,/skillsSourceCommit/);
assert.match(skills,/CONTEXT_USED/);
assert.match(skills,/Do not claim a skill was loaded or executed/);
assert.match(voice,/SkillAuthorityClient/);
assert.match(voice,/lastSkillEvidence/);
assert.match(manifest,/SYSTEM_ALERT_WINDOW/);
assert.match(manifest,/PocketOverlayService/);
assert.match(manifest,/PocketBootReceiver/);
assert.equal(bindingJson.bindings.find(x=>x.id==="voice-fabric").voicePackageId,"agent-lee-voice-one");
assert.equal(bindingJson.bindings.find(x=>x.id==="formula").executionClaim,"NOT_EXECUTED_UNLESS_RECEIPT_RETURNED");
assert.match(bindingJson.bindings.find(x=>x.id==="agent-skills").phoneBinding,/REMOTE_MCP_PENDING/);

console.log("PASS Pocket secondary-workstation source contract");
