import fs from "node:fs";
import assert from "node:assert/strict";

const root="app/src/main";
const main=fs.readFileSync(root+"/java/industries/leeway/pocket/MainActivity.kt","utf8");
const voice=fs.readFileSync(root+"/java/industries/leeway/pocket/PocketVoiceActivity.kt","utf8");
const voiceHost=fs.readFileSync(root+"/java/industries/leeway/pocket/PocketVoiceHost.kt","utf8");
const overlay=fs.readFileSync(root+"/java/industries/leeway/pocket/PocketOverlayService.kt","utf8");
const bridge=fs.readFileSync(root+"/java/industries/leeway/pocket/DeviceBridgeClient.kt","utf8");
const phoneActions=fs.readFileSync(root+"/java/industries/leeway/pocket/PhoneActionClient.kt","utf8");
const bindings=fs.readFileSync(root+"/java/industries/leeway/pocket/EcosystemBindings.kt","utf8");
const skills=fs.readFileSync(root+"/java/industries/leeway/pocket/SkillAuthorityClient.kt","utf8");
const manifest=fs.readFileSync(root+"/AndroidManifest.xml","utf8");
const gradle=fs.readFileSync("app/build.gradle.kts","utf8");
const embeddedDeviceRuntime=root+"/java/industries/leeway/devicebridge";
const bindingJson=JSON.parse(fs.readFileSync("docs/ecosystem-bindings.json","utf8"));
const profile=JSON.parse(fs.readFileSync(root+"/assets/leeway-authority-profile.json","utf8"));
assert.equal(profile.creator.name,"Leonard J. Lee");
assert.equal(new Set(profile.repositories.map(x=>x.name)).size,9);
assert.equal(profile.imageGeneration.binding,"NOT_BOUND");
assert.match(profile.creator.classification,/NOT_AUTHENTICATION/);

assert.doesNotMatch(main,/TextToSpeech/);
assert.doesNotMatch(voice,/TextToSpeech/);
assert.doesNotMatch(voice,/speechSynthesis/);
assert.match(voice,/SpeechRecognizer/);
assert.match(voiceHost,/LeeWayAndroidVoice/);
assert.match(voiceHost,/DEFAULT_VOICE_ID = "agent-lee-voice-one"/);
assert.match(voiceHost,/agent_voice_one_default_v2/);
assert.doesNotMatch(voiceHost,/device=wasm/);
assert.doesNotMatch(voiceHost,/putString\("selected_id","android-installed-english"\)/);
assert.match(voice,/PocketSpeech.detach/);
assert.doesNotMatch(voice,/WebView\(/);
assert.match(voice,/agent\.chat/);
assert.match(voice,/canonicalFormulaState/);
assert.match(voice,/DeviceBridgeClient/);
assert.match(voice,/EcosystemBindings\.runtimeFabricSnapshot/);
assert.match(voice,/voiceFabricRegistered/);
assert.match(voice,/phoneExecutionNodeRegistered/);
assert.match(phoneActions,/EcosystemBindings\.runtimeFabricSnapshot/);
assert.match(phoneActions,/RUNTIME_FABRIC_PHONE_NODE_UNQUALIFIED/);
assert.match(overlay,/TYPE_APPLICATION_OVERLAY/);
assert.match(overlay,/PocketVoiceActivity/);
assert.match(bridge,/PocketBridgeActivity/);
assert.match(bridge,/POCKET_BOOTSTRAP/);
assert.match(bindings,/ecosystem-bindings\.json/);
assert.match(bindings,/leeway-runtime-fabric\.fly\.dev\/api\/health/);
assert.match(bindings,/leeway-runtime-fabric\.fly\.dev\/api\/components/);
assert.match(bindings,/leeway-runtime-fabric\.fly\.dev\/api\/self-hosted\/status/);
assert.match(bindings,/LEEWAY_CONTROL_PLANE_READY_PASS/);
assert.match(bindings,/provider-fabric/);
assert.match(bindings,/leeway-phone-workstation/);
assert.match(bindings,/PHONE_LOCAL_NATIVE_PACKAGE/);
assert.match(bindings,/LeeWay-Voice-Fabric\/android-bridge\.html/);
assert.doesNotMatch(bindings,/raw\.githubusercontent\.com\/4citeB4U\/Leeway-Runtime-Fabric/);
assert.match(skills,/96ea94dda56e642887e600b54528b69919f0a2e6/);
assert.match(skills,/skillsSourceCommit/);
assert.match(skills,/CONTEXT_USED/);
assert.match(skills,/Do not claim a skill was loaded or executed/);
assert.match(voice,/SkillAuthorityClient/);
assert.match(voice,/lastSkillEvidence/);
assert.match(manifest,/SYSTEM_ALERT_WINDOW/);
assert.match(manifest,/PocketOverlayService/);
assert.match(manifest,/PocketBootReceiver/);
assert.equal(bindingJson.bindings.find(x=>x.id==="voice-fabric").voicePackageId,"agent-lee-voice-one");
assert.equal(bindingJson.bindings.find(x=>x.id==="formula").executionClaim,"NOT_EXECUTED_UNLESS_CANONICAL_FORMULA_RECEIPT_RETURNED");
assert.match(bindingJson.bindings.find(x=>x.id==="runtime-fabric").phoneBinding,/CANONICAL_RUNTIME_FABRIC_REGISTRIES/);
assert.match(bindingJson.bindings.find(x=>x.id==="device-bridge").phoneBinding,/leeway-phone-workstation/);
assert.match(bindingJson.bindings.find(x=>x.id==="voice-fabric").phoneBinding,/leeway-voice-fabric/);
assert.equal(fs.existsSync(embeddedDeviceRuntime),false);
assert.match(gradle,/versionCode = 25/);
assert.match(gradle,/0\.3\.6-runtime-fabric-live-binding-rc2/);
assert.match(bindingJson.bindings.find(x=>x.id==="agent-skills").phoneBinding,/RUNTIME_FABRIC_SKILLS_UNIVERSITY/);

console.log("PASS Pocket secondary-workstation source contract");
